### ISSUE TITLE
ASSERT failed when using https://abap-openapi.github.io/web-openapi-client/ with Variant Configuration Service

### ISSUE THREAD

**Issue by gregorwolf** [abap-openapi/abap-openapi#84]
Hello,

I'm using https://abap-openapi.github.io/web-openapi-client/ with the JSON file downloaded from https://api.sap.com/api/ProductConfigurationService/overview. Unfortunately I get only this error:

```
Error: ASSERT failed
    at Statements.assert (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:3215:15)
    at zcl_oapi_graph.pop (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:280917:21)
    at async zcl_oapi_references.sort_schemas (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:281879:20)
    at async zcl_oapi_references.normalize (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:281857:5)
    at async zcl_oapi_generator_v2.run (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:280709:32)
    at async zcl_oapi_generator.generate_v2 (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:280653:20)
    at async jsonChanged (https://abap-openapi.github.io/web-openapi-client/app.bundle.js:255572:20)
```

what's the best way to debug so I can contribute a correction?

Best Regards
Gregor

**Comment by larshp** [comment]
A: install the code https://github.com/abap-openapi/abap-openapi via abapGit. Pass the schema to `ZCL_OAPI_GENERATOR=>GENERATE_V2`

B: run locally via transpiler

**Comment by larshp** [comment]
are there any cycles in the definitions?, 

![image](https://user-images.githubusercontent.com/5888506/196184533-11c0b858-162b-45ef-895b-f2acdc2d40b8.png)

**Comment by larshp** [comment]
locally: add a folder `test008`, add a `spec.json`,

![image](https://user-images.githubusercontent.com/5888506/196185233-1967f2b3-3570-4703-a4aa-baaef67bea39.png)

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/196186948-28cf5813-4213-412e-97b5-213ab6c37773.png)

**Comment by larshp** [comment]
abap-openapi generates ABAP types corresponding to the types in the schema. TYPES does not allow for cyclic definitions, if you dont need the cyclic definitions, or only to a certain point, suggest manually modifying the schema

**Comment by gregorwolf** [comment]
Thank you @larshp. With a reduced schema I'm able to do the generation. What options are there to get better error output and maybe show what cyclic definitions exist?

**Comment by larshp** [comment]
considering:
A: throw an exception
B: skip the stuff that is cyclic and give warnings

probably "A" will be the first solution
